# Generated by Django 3.0.3 on 2020-08-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_cn', '0002_auto_20200825_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='picture',
            field=models.ImageField(null=True, upload_to='employee'),
        ),
    ]
