# Generated by Django 3.0.3 on 2020-08-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_cn', '0004_auto_20200826_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(null=True, upload_to='emplyee'),
        ),
    ]
