# Generated by Django 3.0.3 on 2020-08-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_cn', '0006_auto_20200826_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.IntegerField(blank=True, choices=[(1, 'Investment partner'), (2, 'Investment manager'), (3, 'Global concept'), (4, 'Investment adviser'), (5, 'Post-investment'), (6, 'Legal'), (7, 'Operation')], null=True),
        ),
    ]
