# Generated by Django 3.0.3 on 2020-09-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_cn', '0008_auto_20200826_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='enterprise',
            name='picture_owner',
            field=models.ImageField(null=True, upload_to='owner'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='trademark',
            field=models.ImageField(null=True, upload_to='trademark'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='picture',
            field=models.ImageField(null=True, upload_to='employee'),
        ),
    ]
