# Generated by Django 3.0.3 on 2020-09-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sig_cn', '0009_auto_20200915_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title'], 'verbose_name': 'aaa'},
        ),
    ]
