# Generated by Django 3.0.3 on 2020-09-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_cn', '0011_auto_20200915_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('Investment partner', 'Investment partner'), ('Investment manager', 'Investment manager'), ('Global management', 'Global management'), ('Investment adviser', 'Investment adviser'), ('Post-investment', 'Post-investment'), ('Legal', 'Legal'), ('Operation', 'Operation')], max_length=30, null=True),
        ),
    ]
