# Generated by Django 3.0.3 on 2020-09-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sig_cn', '0012_auto_20200928_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='available',
            field=models.BooleanField(null=True),
        ),
    ]
